// Назначаем zoneID вручную по ссылке на триггер (если такие переменные существуют)
// Назначаем zoneID для существующих триггеров (если переменные существуют)
if !(isNil "avanpost_1") then { avanpost_1 setVariable ["zoneID", "avanpost_1"]; };
if !(isNil "avanpost_2") then { avanpost_2 setVariable ["zoneID", "avanpost_2"]; };
if !(isNil "avanpost_3") then { avanpost_3 setVariable ["zoneID", "avanpost_3"]; };
if !(isNil "avanpost_4") then { avanpost_4 setVariable ["zoneID", "avanpost_4"]; };
if !(isNil "avanpost_5") then { avanpost_5 setVariable ["zoneID", "avanpost_5"]; };
if !(isNil "avanpost_6") then { avanpost_6 setVariable ["zoneID", "avanpost_6"]; };
if !(isNil "avanpost_7") then { avanpost_7 setVariable ["zoneID", "avanpost_7"]; };
if !(isNil "avanpost_8") then { avanpost_8 setVariable ["zoneID", "avanpost_8"]; };
if !(isNil "avanpost_9") then { avanpost_9 setVariable ["zoneID", "avanpost_9"]; };
if !(isNil "avanpost_10") then { avanpost_10 setVariable ["zoneID", "avanpost_10"]; };
if !(isNil "avanpost_11") then { avanpost_11 setVariable ["zoneID", "avanpost_11"]; };
if !(isNil "avanpost_12") then { avanpost_12 setVariable ["zoneID", "avanpost_12"]; };
if !(isNil "avanpost_13") then { avanpost_13 setVariable ["zoneID", "avanpost_13"]; };
if !(isNil "avanpost_14") then { avanpost_14 setVariable ["zoneID", "avanpost_14"]; };
if !(isNil "avanpost_15") then { avanpost_15 setVariable ["zoneID", "avanpost_15"]; };
if !(isNil "avanpost_16") then { avanpost_16 setVariable ["zoneID", "avanpost_16"]; };
if !(isNil "avanpost_17") then { avanpost_17 setVariable ["zoneID", "avanpost_17"]; };
if !(isNil "avanpost_18") then { avanpost_18 setVariable ["zoneID", "avanpost_18"]; };
if !(isNil "avanpost_19") then { avanpost_19 setVariable ["zoneID", "avanpost_19"]; };
if !(isNil "avanpost_20") then { avanpost_20 setVariable ["zoneID", "avanpost_20"]; };
if !(isNil "avanpost_21") then { avanpost_21 setVariable ["zoneID", "avanpost_21"]; };
if !(isNil "avanpost_22") then { avanpost_22 setVariable ["zoneID", "avanpost_22"]; };
if !(isNil "avanpost_23") then { avanpost_23 setVariable ["zoneID", "avanpost_23"]; };
if !(isNil "avanpost_24") then { avanpost_24 setVariable ["zoneID", "avanpost_24"]; };
if !(isNil "avanpost_25") then { avanpost_25 setVariable ["zoneID", "avanpost_25"]; };
if !(isNil "avanpost_26") then { avanpost_26 setVariable ["zoneID", "avanpost_26"]; };
if !(isNil "avanpost_27") then { avanpost_27 setVariable ["zoneID", "avanpost_27"]; };
if !(isNil "avanpost_28") then { avanpost_28 setVariable ["zoneID", "avanpost_28"]; };
if !(isNil "avanpost_29") then { avanpost_29 setVariable ["zoneID", "avanpost_29"]; };
if !(isNil "avanpost_30") then { avanpost_30 setVariable ["zoneID", "avanpost_30"]; };
if !(isNil "avanpost_31") then { avanpost_31 setVariable ["zoneID", "avanpost_31"]; };
if !(isNil "avanpost_32") then { avanpost_32 setVariable ["zoneID", "avanpost_32"]; };
if !(isNil "avanpost_33") then { avanpost_33 setVariable ["zoneID", "avanpost_33"]; };
if !(isNil "avanpost_34") then { avanpost_34 setVariable ["zoneID", "avanpost_34"]; };
if !(isNil "avanpost_35") then { avanpost_35 setVariable ["zoneID", "avanpost_35"]; };
if !(isNil "avanpost_36") then { avanpost_36 setVariable ["zoneID", "avanpost_36"]; };
if !(isNil "avanpost_37") then { avanpost_37 setVariable ["zoneID", "avanpost_37"]; };
if !(isNil "avanpost_38") then { avanpost_38 setVariable ["zoneID", "avanpost_38"]; };
if !(isNil "avanpost_39") then { avanpost_39 setVariable ["zoneID", "avanpost_39"]; };
if !(isNil "avanpost_40") then { avanpost_40 setVariable ["zoneID", "avanpost_40"]; };
if !(isNil "avanpost_41") then { avanpost_41 setVariable ["zoneID", "avanpost_41"]; };
if !(isNil "avanpost_42") then { avanpost_42 setVariable ["zoneID", "avanpost_42"]; };
if !(isNil "avanpost_43") then { avanpost_43 setVariable ["zoneID", "avanpost_43"]; };
if !(isNil "avanpost_44") then { avanpost_44 setVariable ["zoneID", "avanpost_44"]; };
if !(isNil "avanpost_45") then { avanpost_45 setVariable ["zoneID", "avanpost_45"]; };
if !(isNil "avanpost_46") then { avanpost_46 setVariable ["zoneID", "avanpost_46"]; };
if !(isNil "avanpost_47") then { avanpost_47 setVariable ["zoneID", "avanpost_47"]; };
if !(isNil "avanpost_48") then { avanpost_48 setVariable ["zoneID", "avanpost_48"]; };
if !(isNil "avanpost_49") then { avanpost_49 setVariable ["zoneID", "avanpost_49"]; };
if !(isNil "avanpost_50") then { avanpost_50 setVariable ["zoneID", "avanpost_50"]; };
if !(isNil "avanpost_51") then { avanpost_51 setVariable ["zoneID", "avanpost_51"]; };
if !(isNil "avanpost_52") then { avanpost_52 setVariable ["zoneID", "avanpost_52"]; };
if !(isNil "avanpost_53") then { avanpost_53 setVariable ["zoneID", "avanpost_53"]; };
if !(isNil "avanpost_54") then { avanpost_54 setVariable ["zoneID", "avanpost_54"]; };
if !(isNil "avanpost_55") then { avanpost_55 setVariable ["zoneID", "avanpost_55"]; };
if !(isNil "avanpost_56") then { avanpost_56 setVariable ["zoneID", "avanpost_56"]; };
if !(isNil "avanpost_57") then { avanpost_57 setVariable ["zoneID", "avanpost_57"]; };
if !(isNil "avanpost_58") then { avanpost_58 setVariable ["zoneID", "avanpost_58"]; };
if !(isNil "avanpost_59") then { avanpost_59 setVariable ["zoneID", "avanpost_59"]; };
if !(isNil "avanpost_60") then { avanpost_60 setVariable ["zoneID", "avanpost_60"]; };
if !(isNil "avanpost_61") then { avanpost_61 setVariable ["zoneID", "avanpost_61"]; };
if !(isNil "avanpost_62") then { avanpost_62 setVariable ["zoneID", "avanpost_62"]; };
if !(isNil "avanpost_63") then { avanpost_63 setVariable ["zoneID", "avanpost_63"]; };
if !(isNil "avanpost_64") then { avanpost_64 setVariable ["zoneID", "avanpost_64"]; };
if !(isNil "avanpost_65") then { avanpost_65 setVariable ["zoneID", "avanpost_65"]; };
if !(isNil "avanpost_66") then { avanpost_66 setVariable ["zoneID", "avanpost_66"]; };
if !(isNil "avanpost_67") then { avanpost_67 setVariable ["zoneID", "avanpost_67"]; };
if !(isNil "avanpost_68") then { avanpost_68 setVariable ["zoneID", "avanpost_68"]; };
if !(isNil "avanpost_69") then { avanpost_69 setVariable ["zoneID", "avanpost_69"]; };
if !(isNil "avanpost_70") then { avanpost_70 setVariable ["zoneID", "avanpost_70"]; };
if !(isNil "avanpost_71") then { avanpost_71 setVariable ["zoneID", "avanpost_71"]; };
if !(isNil "avanpost_72") then { avanpost_72 setVariable ["zoneID", "avanpost_72"]; };
if !(isNil "avanpost_73") then { avanpost_73 setVariable ["zoneID", "avanpost_73"]; };
if !(isNil "avanpost_74") then { avanpost_74 setVariable ["zoneID", "avanpost_74"]; };
if !(isNil "avanpost_75") then { avanpost_75 setVariable ["zoneID", "avanpost_75"]; };
if !(isNil "avanpost_76") then { avanpost_76 setVariable ["zoneID", "avanpost_76"]; };
if !(isNil "avanpost_77") then { avanpost_77 setVariable ["zoneID", "avanpost_77"]; };
if !(isNil "avanpost_78") then { avanpost_78 setVariable ["zoneID", "avanpost_78"]; };
if !(isNil "avanpost_79") then { avanpost_79 setVariable ["zoneID", "avanpost_79"]; };
if !(isNil "avanpost_80") then { avanpost_80 setVariable ["zoneID", "avanpost_80"]; };
if !(isNil "avanpost_81") then { avanpost_81 setVariable ["zoneID", "avanpost_81"]; };
if !(isNil "avanpost_82") then { avanpost_82 setVariable ["zoneID", "avanpost_82"]; };
if !(isNil "avanpost_83") then { avanpost_83 setVariable ["zoneID", "avanpost_83"]; };
if !(isNil "avanpost_84") then { avanpost_84 setVariable ["zoneID", "avanpost_84"]; };
if !(isNil "avanpost_85") then { avanpost_85 setVariable ["zoneID", "avanpost_85"]; };
if !(isNil "avanpost_86") then { avanpost_86 setVariable ["zoneID", "avanpost_86"]; };
if !(isNil "avanpost_87") then { avanpost_87 setVariable ["zoneID", "avanpost_87"]; };
if !(isNil "avanpost_88") then { avanpost_88 setVariable ["zoneID", "avanpost_88"]; };
if !(isNil "avanpost_89") then { avanpost_89 setVariable ["zoneID", "avanpost_89"]; };
if !(isNil "avanpost_90") then { avanpost_90 setVariable ["zoneID", "avanpost_90"]; };
if !(isNil "avanpost_91") then { avanpost_91 setVariable ["zoneID", "avanpost_91"]; };
if !(isNil "avanpost_92") then { avanpost_92 setVariable ["zoneID", "avanpost_92"]; };
if !(isNil "avanpost_93") then { avanpost_93 setVariable ["zoneID", "avanpost_93"]; };
if !(isNil "avanpost_94") then { avanpost_94 setVariable ["zoneID", "avanpost_94"]; };
if !(isNil "avanpost_95") then { avanpost_95 setVariable ["zoneID", "avanpost_95"]; };
if !(isNil "avanpost_96") then { avanpost_96 setVariable ["zoneID", "avanpost_96"]; };
if !(isNil "avanpost_97") then { avanpost_97 setVariable ["zoneID", "avanpost_97"]; };
if !(isNil "avanpost_98") then { avanpost_98 setVariable ["zoneID", "avanpost_98"]; };
if !(isNil "avanpost_99") then { avanpost_99 setVariable ["zoneID", "avanpost_99"]; };
if !(isNil "avanpost_100") then { avanpost_100 setVariable ["zoneID", "avanpost_100"]; };

if (isServer) then {
    private _zoneConfig = call compile preprocessFileLineNumbers "zone_config.sqf";
    {
        private _zoneID = _x select 0;
        private _radiusX = 100;
        private _radiusY = 100;
        private _trigger = objNull;
        {
            if (_x getVariable ["zoneID", ""] == _zoneID) exitWith { _trigger = _x };
        } forEach allMissionObjects "EmptyDetector";
        if (!isNull _trigger) then {
            _radiusX = (triggerArea _trigger) select 0;
            _radiusY = (triggerArea _trigger) select 1;
        };
        private _captured = profileNamespace getVariable [_zoneID, false];
        private _color = if (_captured) then {"ColorGreen"} else {"ColorRed"};
        private _markerName = format ["marker_%1", _zoneID];
        private _marker = createMarker [_markerName, getMarkerPos _markerName];
        _marker setMarkerShape "ELLIPSE";
        _marker setMarkerSize [_radiusX, _radiusY];
        _marker setMarkerColor _color;
        _marker setMarkerAlpha 0.5;
        _marker setMarkerPos getPos _trigger;
        _marker setMarkerText (if (_captured) then {"Республиканский аванпост"} else {""});
    } forEach _zoneConfig;
};
